module.exports = {
    'likes' : '{ likes , number } me gusta',
    'logout' : 'Salir',
    'english' : 'Inglés',
    'spanish' : 'Español',
    'signup.subheading' : 'Regístrate para ver fotos de todas las personas',
    'signup.facebook' : 'Iniciar sesión con Facebook',
    'signup.text' : 'Iniciar Sesión',
    'email' : 'Correo electrónico',
    'signup.username' : 'Nombre de Usuario',
    'fullname' : 'Nombre Completo',
    'password' : 'Contraseña',
    'signup.call-to-action' : 'Regístrate',
    'signup.have-account' : ' Tienes una cuenta ?',
    'signin' : 'Entrar',
    'signin.not-have-account' : ' No tienes una cuenta ?',
    'language' : 'Idioma',
     'upload-picture' : "Subir Foto",
     'upload' : "Subir"
}